version: '3'
services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root      
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data  
    networks:
      - my_network

  app-go:
    image: golang
    ports:
     - "6060:8080"
    volumes:
      - ./app:/var/app
    command: "tail -f /dev/null"
    depends_on:
      - postgres
    networks:
      - my_network
    environment:
      - BD_HOST=postgres
      
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "user"
      PGADMIN_DEFAULT_PASSWORD: "p@inelP0stgr3"
    ports:
      - "54321:80"
    depends_on:
      - postgres
    networks:
      - my_network

networks:
  my_network:
    driver: bridge