# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test:
    runs-on: ubuntu-latest
    env:
      BD_HOST: ""
    steps:
    - uses: actions/checkout@v3

    - name: Get IP Address
      run: |
          DEPLOYED_IP=$(curl -s ifconfig.me)
          echo "DEPLOYED_IP=$DEPLOYED_IP" >> $GITHUB_ENV

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build-DB 
      run: docker-compose build

    - name: Create-DB
      run: docker-compose up  && sleep 10 && docker-compose ps
    
    - name: Update Depency
      working-directory: ./app
      run: go mod tidy

    - name: Test
      working-directory: ./app
      run: go test -v main_test.go

    - name: Build
      working-directory: ./app
      run: go build -v main.go
      
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      working-directory: ./app
      run: go build -v main.go
